name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Run custom Python action
        uses: ./.github/actions/actions-pull-request
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: 'My New Pull Request'
          head: 'feature-branch'
          base: 'main'
